config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  # Main Navigation Menu
  get '/contact_us', to: 'contact#index'
  get '/pricing', to: 'pricing#index'
  get '/software', to: 'software#index'
  get '/support', to: 'support#index'

  # User menu
  get '/dashboard', to: 'dashboard#index'


  resources :properties do
    collection do
      get :setup
    end
  end
  resources :users do
    collection do
      post :authenticate
      get :sign_in
      post :sign_out
    end
  end

  root to: 'home#index'
end

app/models/address.rb
class Address < ApplicationRecord
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/name.rb
class Name < ApplicationRecord
  belongs_to :profile
end

app/models/phone.rb
class Phone < ApplicationRecord
  belongs_to :profile
end

app/models/profile.rb
class Profile < ApplicationRecord
  belongs_to :user

  has_one :address, as: :addressable
  has_one :name
  has_one :phone

  accepts_nested_attributes_for :name
  accepts_nested_attributes_for :address
  accepts_nested_attributes_for :phone
end

app/models/property.rb
class Property < ApplicationRecord
  belongs_to :propertyable, polymorphic: true
  belongs_to :user
end

app/models/transaction.rb
class Transaction < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password validations: true
  attr_accessor :password_confirmation

  has_one :profile
  has_many :properties
  accepts_nested_attributes_for :profile

  validates_presence_of :email, :password_digest
  validates_uniqueness_of :email
end

app/controllers/contact_controller.rb
class ContactController < ApplicationController
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index

  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  MENU_OPTIONS = %w[dash directory documents finances
                    reports events forms].map(&:capitalize)

  rescue_from ActionController::ParameterMissing do
    logger.error(t 'errors.global.parameter_missing')
    redirect_to sign_in_users_path
  end

  def new
    @user = User.new.tap do |user|
      user.profile = Profile.new.tap do |profile|
        profile.name    = Name.new
        profile.address = Address.new
        profile.phone   = Phone.new
      end
    end
  end

  def sign_in
    @user = User.new
  end

  def create
    @user = User.new(user_params)

    if @user.save
      return redirect_to(dashboard_path)
    end

    render :new
  end

  def sign_out
    session[:user_id] = nil
    redirect_to sign_in_users_path
  end

  def authenticate
    @user = User.find_by_email(user_params[:email])

    if @user && @user.authenticate(user_params[:password])
      session[:user_id] = @user.id
      redirect_to dashboard_path
    else
      redirect_to sign_in_users_path
    end
  end

  private

  def user_params
    params.require(:user).permit(:email, :password, :password_confirmation,
                                 profile_attributes:
                                     [name_attributes:    [:first, :last],
                                      address_attributes: [:address1, :address2, :city, :state, :country, :zip_code],
                                      phone_attributes:   [:number]])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def label_with_error_info(key, form, model)
    label = form.label key
    return label if model.errors[key].blank?

    label.html_safe + model.errors[key].map { |error_item| '<span class="error-item">' + error_item + '</span>' }.join.html_safe
  end

  def page_header(value)
    ('<div class="page-header"><h1>' +
        value +
        '</h1></div>').html_safe
  end

  def authenticated?
    @authenticated
  end
end

app/helpers/contact_helper.rb
module ContactHelper
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/pricing_helper.rb
module PricingHelper
end

app/helpers/properties_helper.rb
module PropertiesHelper
end

app/helpers/software_helper.rb
module SoftwareHelper
end

app/helpers/support_helper.rb
module SupportHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Hoam</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'partials/navigation' %>
    <%= render 'partials/dash/navigation_bar' if authenticated? %>

    <div id="body" class="p-3">
      <%= yield %>
    </div>
  </body>
</html>

app/views/partials/_error.html.erb
<% unless model.errors.blank? %>
  Show Flash errors here.
<% end %>

app/views/partials/_navigation.html.erb
<nav class="navbar navbar-light navbar-expand-lg align-items-end" id="main-nav">
  <a class="navbar-brand" href="/">
    <%= image_tag 'hoam - main.png' %>
  </a>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav ml-auto">
      <li class="nav-item active">
        <%= link_to (t 'home'), root_path, class: 'nav-link' %>
      </li>
      <li class="nav-item active">
        <%= link_to (t 'software'), software_path, class: 'nav-link' %>
      </li>
      <li class="nav-item active">
        <%= link_to (t 'pricing'), pricing_path, class: 'nav-link' %>
      </li>
      <li class="nav-item active">
        <%= link_to (t 'contact'), contact_us_path, class: 'nav-link' %>
      </li>
      <li class="nav-item active">
        <%= link_to (t 'support'), support_path, class: 'nav-link' %>
      </li>
      <li class="nav-item active">
        <% if @authenticated %>
          <%= button_to (t 'sign_out'), sign_out_users_path, { class: 'btn btn-primary sharp ml-auto' } %>
        <% else %>
          <%= link_to (t 'sign_in'), sign_in_users_path, { class: 'btn btn-primary sharp ml-auto' } %>
        <% end %>
      </li>
    </ul>
  </div>
</nav>

app/views/partials/dash/_navigation_bar.html.erb
<nav class="navbar navbar-expand-lg navbar-dark align-items-start" id="user-nav">
  <select class="col-sm-12 navbar-toggler" data-toggle="collapse" data-target="#user-nav-content" aria-controls="user-nav-content" aria-expanded="false" aria-label="Toggle user navigation bar.">
    <% UsersController::MENU_OPTIONS.each do |item| %>
      <option><%= item %></option>
    <% end %>
  </select>

  <div class="collapse navbar-collapse" id="user-nav-content">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <%= link_to I18n.t('dash'), dashboard_path, {class: 'nav-link'} %>
      </li>
      <li class="nav-item active">
        <%#= link_to I18n.t('directory'), directories_path, {class: 'nav-link'} %>
      </li>
      <li class="nav-item active">
        <%#= link_to I18n.t('documents'), documents_path, {class: 'nav-link'} %>
      </li>
      <li class="nav-item active">
        <%#= link_to I18n.t('finances'), finances_path, {class: 'nav-link'} %>
      </li>
      <li class="nav-item active">
        <%#= link_to I18n.t('reports'), reports_path, {class: 'nav-link'} %>
      </li>
      <li class="nav-item active">
        <%#= link_to I18n.t('events'), events_path, {class: 'nav-link'} %>
      </li>
      <li class="nav-item active">
        <%#= link_to I18n.t('forms'), forms_path, {class: 'nav-link'} %>
      </li>
    </ul>
  </div>
</nav>

app/views/partials/person/_profile.html.erb
<%= g.fields_for :profile do |p| %>
  <div class="form-group">

    <%= p.fields_for :name do |h| %>
      <div class="header">Name</div>
      <%= h.label :first, t('form.profile.first') %>
      <%= h.text_field :first, {class: 'form-control'} %>

      <%= h.label :last, t('form.profile.last') %>
      <%= h.text_field :last, {class: 'form-control'} %>
    <% end %>
  </div>

  <div class="form-group">
    <%= p.fields_for :address do |i| %>
      <div class="header">Billing Address</div>
      <%= i.label :address1, t('form.address.1') %>
      <%= i.text_field :address1, {class: 'form-control'} %>

      <%= i.label :address2, t('form.address.2') %>
      <%= i.text_field :address2, {class: 'form-control'} %>

      <%= i.label :city, t('form.address.city') %>
      <%= i.text_field :city, {class: 'form-control'} %>

      <%= i.label :state, t('form.address.state') %>
      <%= i.text_field :state, {class: 'form-control'} %>

      <%= i.label :zip_code, t('form.address.zip_code') %>
      <%= i.text_field :zip_code, {class: 'form-control'} %>

      <%= i.label :country, t('form.address.country') %>
      <%= i.text_field :country, {class: 'form-control'} %>
    <% end %>
  </div>

  <div class="form-group">
    <%= p.fields_for :phone do |j| %>
      <div class="header">Phone Number</div>
      <%= j.label :number, t('form.phone') %>
      <%= j.text_field :number, {class: 'form-control'} %>
      <small class="form-text"><%= t 'form.hint.phone' %></small>
      </div>
    <% end %>
<% end %>