config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  # Main Navigation Menu
  get '/contact_us', to: 'contact#index'
  get '/pricing', to: 'pricing#index'
  get '/software', to: 'software#index'
  get '/support', to: 'support#index'

  # User menu
  get '/dashboard', to: 'dashboard#index'


  resources :properties do
    collection do
      get :setup
    end
  end
  resources :users do
    collection do
      post :authenticate
      get :sign_in
      post :sign_out
    end
  end

  root to: 'home#index'
end

app/models/address.rb
class Address < ApplicationRecord
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/name.rb
class Name < ApplicationRecord
  belongs_to :profile
end

app/models/phone.rb
class Phone < ApplicationRecord
  belongs_to :profile
end

app/models/profile.rb
class Profile < ApplicationRecord
  belongs_to :user

  has_one :address, as: :addressable
  has_one :name
  has_one :phone

  accepts_nested_attributes_for :name
  accepts_nested_attributes_for :address
  accepts_nested_attributes_for :phone
end

app/models/property.rb
class Property < ApplicationRecord
  belongs_to :propertyable, polymorphic: true
  belongs_to :user
end

app/models/transaction.rb
class Transaction < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password validations: true
  attr_accessor :password_confirmation

  has_one :profile
  has_many :properties
  accepts_nested_attributes_for :profile

  validates_presence_of :email, :password_digest
  validates_uniqueness_of :email
end

app/controllers/contact_controller.rb
class ContactController < ApplicationController
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index

  end
end

app/controllers/pricing_controller.rb
class PricingController < ApplicationController
end

app/controllers/software_controller.rb
class SoftwareController < ApplicationController
  def index

  end
end

app/controllers/support_controller.rb
class SupportController < ApplicationController
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  MENU_OPTIONS = %w[dash directory documents finances
                    reports events forms].map(&:capitalize)

  rescue_from ActionController::ParameterMissing do
    logger.error(t 'errors.global.parameter_missing')
    redirect_to sign_in_users_path
  end

  def new
    @user = User.new.tap do |user|
      user.profile = Profile.new.tap do |profile|
        profile.name    = Name.new
        profile.address = Address.new
        profile.phone   = Phone.new
      end
    end
  end

  def sign_in
    @user = User.new
  end

  def create
    @user = User.new(user_params)

    if @user.save
      return redirect_to(dashboard_path)
    end

    render :new
  end

  def sign_out
    session[:user_id] = nil
    redirect_to sign_in_users_path
  end

  def authenticate
    @user = User.find_by_email(user_params[:email])

    if @user && @user.authenticate(user_params[:password])
      session[:user_id] = @user.id
      redirect_to dashboard_path
    else
      redirect_to sign_in_users_path
    end
  end

  private

  def user_params
    params.require(:user).permit(:email, :password, :password_confirmation,
                                 profile_attributes:
                                     [name_attributes:    [:first, :last],
                                      address_attributes: [:address1, :address2, :city, :state, :country, :zip_code],
                                      phone_attributes:   [:number]])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def label_with_error_info(key, form, model)
    label = form.label key
    return label if model.errors[key].blank?

    label.html_safe + model.errors[key].map { |error_item| '<span class="error-item">' + error_item + '</span>' }.join.html_safe
  end

  def page_header(value)
    ('<div class="page-header"><h1>' +
        value +
        '</h1></div>').html_safe
  end

  def authenticated?
    @authenticated
  end
end

app/helpers/contact_helper.rb
module ContactHelper
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/pricing_helper.rb
module PricingHelper
end

app/helpers/properties_helper.rb
module PropertiesHelper
end

app/helpers/software_helper.rb
module SoftwareHelper
end

app/helpers/support_helper.rb
module SupportHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/partials/user/_credentials.html.erb
<div class="form-group">
  <%= h.label :email %>
  <%= h.text_field :email, { class: 'form-control' } %>
  <% unless sign_in %>
    <small class="form-text"><%= t 'form.hint.email' %></small>
  <% end %>
</div>

<div class="form-group">
  <%= h.label :password, t('form.password') %>
  <%= h.password_field :password, { class: 'form-control' } %>
  <% unless sign_in %>
    <small class="form-text"><%= t 'form.hint.password' %></small>
  <% end %>
</div>

app/views/users/authenticate.html.erb
<h1>Users#authenticate</h1>
<p>Find me in app/views/users/authenticate.html.erb</p>

app/views/users/new.html.erb
<%= render partial: 'partials/error', locals: {model: @user} %>

<%= form_with(model: @user, local: true) do |f| %>
  <div class="col-md-6 col-sm-12">
    <%= render partial: 'partials/person/profile', locals: {g: f} %>


    <%= render partial: 'partials/user/credentials', locals: {h: f, sign_in: false} %>

    <div class="form-group">
      <%= label_with_error_info :password_confirmation, f, @user %>

      <%= f.password_field :password_confirmation, {class: 'form-control'} %>
      <small class="form-text"><%= t 'form.hint.password_confirmation' %></small>
    </div>

    <%= f.submit t('form.create_account'), class: 'btn btn-primary blue' %>
  </div>
<% end %>

app/views/users/sign_in.html.erb
<%= form_for @user, url: authenticate_users_path do |f| %>
  <div class="p-2">
<%= render partial: 'partials/user/credentials', locals: {h: f, sign_in: true} %>
<%= f.submit t('form.sign_in'), class: 'btn btn-primary' %>
  </div>
<% end %>